services:
  necesse:
    container_name: NecesseGameServer
    build: .
    restart: always
    ports:
      -  14159:14159/udp
    environment:
      MOTD: Hello There!
      PASSWORD: SomethingReallySecure
      SLOTS: 25
      PAUSE: 1
    volumes:
      - ./data/saves:/necesse_server/saves
      - ./data/logs:/necesse_server/logs
      # If you can't abide downloading the entire game server (it's not huge)
      # each time a new container is spawned (I didn't want to bake the game
      # files into the image), you can mount the entire game directory as
      # a volume. This way steamcmd will be able to update the game
      # files (as they will persist). To do this, comment out the
      # above two lines and uncomment the below.
      # - ./data:/necesse_server
